//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public double Total { get; set; }
        public int PaymentType_Id { get; set; }
        public string User_Username { get; set; }
        public int Receipt_Id { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual User User { get; set; }
    }
}
