//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gear.Files
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentRating
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Rating { get; set; }
        public int Comment_Id { get; set; }
        public string User_Username { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
