//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gear.Files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Contents { get; set; }
        public short Seen { get; set; }
        public string User_Username { get; set; }
        public int ChatRoom_Id { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
    }
}
